### ISSUE TITLE
Create a flow chart of app usage

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#1]
For a better idea of scope and functionality, Mushon should expand on [this document](https://docs.google.com/document/d/1NQYj7rVI-r1yEESQkwb2pUz2GKzL6FIG1mElOu3vsYg/edit#heading=h.8o3gi7bdoaru) by laying out the use flow of the app screens. Based on this flow we can start drafting more specific needs and create more issues for development.

**Comment by mushon** [comment]
Here's a very low fidelity sketch for us to start working with.
I explain each step in the [User Flow](https://github.com/Gizra/public_education/wiki/User-Flow) wiki page and after getting some feedback I will reiterate and obviously develop more high fidelity mockups for key screens.
![Public Education mobile app flow](https://f.cloud.github.com/assets/27123/1079888/9909353e-1554-11e3-881b-b6cf46e24614.JPG)

**Comment by mushon** [comment]
@niryariv would love to get your (/the rest's) feedback / answer any questions here or over phone / in person.

**Comment by niryariv** [comment]
(leaving out the comments re the specific app, since it's changing - per our call)

some initial comments (btw i separated the items to webapp/phonegap app to make it clearer - hope that's cool):
- "accompanied by the lips moving animation" - just to make sure, I assume we're talking about some generic moving lips GIF?
- "Tapping on the '+' sign from within the Phonegap app would zoom out to allow the user to choose the location they would like to address their command towards" - not sure I got it. Isn't the app all about recording? what does the user see when they first open the app?

**Comment by mushon** [comment]
- By "accompanied by the lips moving animation" I'm referring to an animation that I will provide. It will either be an animated gif or a canvas based patch. 
- The app = the web app + recording. When the user opens the app they see a map that locates their current location and allows them to either walk around to 'collect' commands or create a new one (the scenario that starts with tapping the '+' sign)

I hope this makes more sense.
