### ISSUE TITLE
Upload app to Android

### ISSUE THREAD

**Issue by amitaibu** [Gizra/public_education#123]

**Comment by ceoaliongroo** [comment]
requesting image #140

**Comment by ceoaliongroo** [comment]
@amitaibu @mushon  we need to realize a Developer Registration, what email and information use?, and what it the information to charge of 25$ fee one time?

https://play.google.com/apps/publish/signup/#

![developer registration](https://f.cloud.github.com/assets/2622152/1465329/e01e5ebe-455f-11e3-8024-3e696454e11e.png)

Exta information:
http://goo.gl/d10bWA

**Comment by amitaibu** [comment]
@mushon ^^

**Comment by ceoaliongroo** [comment]
@mushon We have already an Android build in TestFight but but without the icons, work ok the installation.
![android](https://f.cloud.github.com/assets/2622152/1471882/400105f4-45f4-11e3-8e8c-e2dcdc80803f.png)

## To publish an Alpha version we need:

![google play-alpha](https://f.cloud.github.com/assets/2622152/1472014/db87449a-45f7-11e3-9a5e-47fcd47b2b63.png)

![no-publish](https://f.cloud.github.com/assets/2622152/1472007/b885622e-45f7-11e3-9d49-8282160d26b6.png)
- [ ] The hi-res icons. and #140 
  ![icons-android](https://f.cloud.github.com/assets/2622152/1472013/cdff84f4-45f7-11e3-88f8-33b4efd8e8ef.png)
- [ ]  Screenshots (Maybe we can use the iphone images without the status icons of the iphone. because we are uploading to alpha.) 
  ![screenshoots android](https://f.cloud.github.com/assets/2622152/1472020/fab209d6-45f7-11e3-95c5-16bb22038c64.png)

@mushon please,
- [ ] Check the Keystore Information (Certificate) used to sing the APK of Android.
  ![kaystore-private-mushon-android](https://f.cloud.github.com/assets/2622152/1472015/f1422a02-45f7-11e3-8a17-7f47054231d8.png)

Thanks

**Comment by mushon** [comment]
I updated #140, is there anything else you're waiting for from my end?

**Comment by ceoaliongroo** [comment]
@amitaibu @mushon Apk Published.

Waiting for Google Play feedback (with the URL of the store) or listed in the store.

![publish-android](https://f.cloud.github.com/assets/2622152/1508200/a1384834-49df-11e3-9548-c5b9a8eb3228.png)

Also there is a build in testflight

**Comment by ceoaliongroo** [comment]
Publish in alpha stage to test, the following link have to work with the beta tester but still do not wotk:

https://play.google.com/apps/testing/com.gizra.publiceducation

I think we have to wait some time to test or listed, because the status of the APK is published in the Google play Store
